config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  namespace :admin do
    get 'rest_books/index'
  end
  namespace :admin do
    get 'hottest_products/index'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web, at: '/sidekiq'
  scope "(:locale)", :locale => /en|vi/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }
    devise_scope :user do
      get "signin", to: "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      post "signin" => "devise/sessions#create"
    end
    root 'static_pages#index'
    resources :books, only: :show do
      put :update_visited
    end
    resources :wishlists
    resources :carts do
      collection do
        delete "destroy_all_cart"
      end
    end
    resources :orders
    resources :categories, only: :show
    resources :notifications
    resources :authors
    # get "/modalbook", to: "static_pages#modalbook"
    namespace :admin do
      root 'static_pages#index'
      resources :categories
      resources :roles
      resources :authors
      resources :users
      resources :books
      resources :orders
      resources :notifications, only: [:update, :index]
      resources :statistic_orders, only: :index
      resources :hottest_products, only: :index
      resources :rest_books, only: :index
    end
  end
  mount ActionCable.server => '/cable'
end

app/controllers/admin/static_pages_controller.rb
module Admin
  class StaticPagesController < AdminBaseController
    def index
      @order_pending_count = Order.status_pending_count
      @user_count = User.count
      @visited_book = Book.sum(:visited)
      @qty_book = Book.sum(:quantity)
      date_seven_days = (Date.parse(I18n.l(Date.today-7.days))..Date.parse(I18n.l(Date.today))).to_a
      date_seven_days.map! {|b| [I18n.l(b), 0]}

      orders_seven_days_ago = Order.order_statistic_seven_days_ago.group_by {|c| c.created_at.to_date}
      orders_get = orders_seven_days_ago.map {|a,b| ([I18n.l(a), b.count])}
      @orders = (orders_get + date_seven_days).uniq(&:first).sort

      @order_status = Order.group(:status).count
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @books = StaticPagesService.new(params).excecute
    @top_books = Book.top_product
  end

  # def modalbook

  # end
end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_arrival.html.erb
<div role="tabpanel" class="tab-pane fade in active" id="arrival">
  <div class="featured-product-list indicator-style">
    <div class="row">
      <% @books.each do |book| %>
        <% if user_signed_in? %>
          <% wishlist = Wishlist.find_by user_id: current_user.id, book_id: book.id %>
        <% end %>
        <div class="col-md-3">
          <div class="single-banner">
            <div class="product-wrapper">
              <%= link_to book_path(book), class: "single-banner-image-wrapper check-visited", data: {book_id: book.id} do %>
                <%= image_tag book.image.url %>
                <div class="price"><%= format_money_amount book.money %></div>
                <div class="rating-icon">
                  <i class="fas fa-star icolor"></i>
                  <i class="fas fa-star icolor"></i>
                  <i class="fas fa-star icolor"></i>
                  <i class="fas fa-star"></i>
                  <i class="fas fa-star"></i>
                </div>
              <% end %>
              <div class="product-description">
                <div class="functional-buttons button-reaction-<%= book.id %>">
                  <%= render "button_book", book: book, wishlist: wishlist %>
                </div>
              </div>
            </div>
            <div class="banner-bottom text-center">
              <%= link_to book.name, book_path(book), class: "check-visited", data: {book_id: book.id} %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div id="pagination">
      <%= paginate @books %>
    </div>
  </div>
</div>
<div class="modal hide fade" id="productModal" role="dialog"></div>

app/views/static_pages/_button_book.html.erb
<%= link_to carts_path(id: book.id, price: book.money, qty: 1), remote: true, method: :post, title: "Add to cart" do %>
  <i class="fas fa-shopping-cart"></i>
<% end %>
  <% if user_signed_in? && book.wishlist_by_user?(current_user) %>
    <%= link_to wishlist_path(wishlist, book_id: book.id), method: :delete, remote: true, title: "Remove from Wishlist", class: "remove-wishlist" do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to wishlists_path(book_id: book.id), method: :post, remote: true, title: "Add to Wishlist", class: "add-wishlist" do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
<%= link_to "#", remote: true do %>
  <i class="fas fa-compress"></i>
<% end %>

app/views/static_pages/_quick_view.html.erb
<div id="quickview-wrapper">
  <!-- Modal -->
  <!-- <div class="modal fade" id="productModal" role="dialog"> -->
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <div class="modal-product">
            <div class="product-images">
              <div class="main-image images">

              </div>
            </div>
            <div class="product-info">
              <h1>Frame Princes Cut Diamond</h1>
              <div class="price-box">
                <p class="s-price"><span class="special-price"><span class="amount">$280.00</span></span></p>
              </div>
              <a href="product-details.html" class="see-all">See all features</a>
              <div class="quick-add-to-cart">
                <form method="post" class="cart">
                  <div class="numbers-row">
                    <input type="number" id="french-hens" value="3">
                  </div>
                  <button class="single_add_to_cart_button" type="submit">Add to cart</button>
                </form>
              </div>
              <div class="quick-desc">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero vulputate rutrum. Morbi ornare lectus quis justo gravida semper. Nulla tellus mi, vulputate adipiscing cursus eu, suscipit id nulla.
              </div>
              <div class="social-sharing">
                <div class="widget widget_socialsharing_widget">
                  <h3 class="widget-title-modal">Share this product</h3>
                  <ul class="social-icons">
                    <li><a target="_blank" title="Facebook" href="#" class="facebook social-icon"><i class="fab fa-facebook"></i></a></li>
                    <li><a target="_blank" title="Twitter" href="#" class="twitter social-icon"><i class="fab fa-twitter"></i></a></li>
                    <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="fab fa-pinterest"></i></a></li>
                    <li><a target="_blank" title="Google +" href="#" class="gplus social-icon"><i class="fab fa-google-plus"></i></a></li>
                    <li><a target="_blank" title="LinkedIn" href="#" class="linkedin social-icon"><i class="fab fa-linkedin"></i></a></li>
                  </ul>
                </div>
              </div>
            </div><!-- .product-info -->
          </div>
        </div>
      </div>
    </div>
  <!-- </div> -->
<!-- </div> -->

app/views/static_pages/_shop.html.erb
<div class="featured-product-area section-padding">
  <h2 class="section-title"><%= t "feature" %></h2>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="tab-menu">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li class="first-item active">
              <%= link_to root_path(criteria: :default), remote: true, class: "default" do %>
                New Arrival
              <% end %>
            </li>
            <li>
              <%= link_to root_path(criteria: :low_to_high), remote: true, class: "low_to_high" do %>
                LOW TO HIGH
              <% end %>
            </li>
            <li>
              <%= link_to root_path(criteria: :high_to_low), remote: true, class: "high_to_low" do %>
                LOW TO HIGH
              <% end %>
            </li>
            <li>
              <%= link_to root_path(criteria: :most_view), remote: true, class: "best_seller" do %>
                MOST VIEW
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="product-list tab-content">
        <%= render "static_pages/arrival" %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<%= render "layouts/banner" %>
<div class="online-banner-area">
    <div class="container">
        <div class="banner-title text-center">
            <h2><span><%= t "top" %></span></h2>
        </div>
        <div class="row">
            <div class="banner-list">
              <% @top_books.each do |book| %>
                <div class="col-md-4 col-sm-6">
                    <div class="single-banner">
                        <%= link_to book_path(book) do %>
                          <%= image_tag book.image.url %>
                        <% end %>
                        <div class="price"><%= format_money_amount book.money %></div>
                        <div class="banner-bottom text-center">
                          <%= link_to book.name, book_path(book) %>
                        </div>
                    </div>
                </div>
              <% end %>
            </div>
        </div>
    </div>
</div>
<%= render "static_pages/shop" %>
<script type="text/javascript">
<% if flash[:success] %>
  toastr.success("<%= flash[:success] %>")
<% end %>
<% if flash[:warning] %>
  toastr.warning("<%= flash[:warning] %>")
<% end %>
<% if flash[:danger] %>
  toastr.error("<%= flash[:danger] %>")
<% end %>
</script>>

app/views/static_pages/index.js.erb
<% if params[:criteria].present? %>
  $('.product-list').html('<%= j render "static_pages/arrival" %>')
<% end %>

app/views/static_pages/modalbook.js.erb
$('#productModal').html("<%= j render 'quick_view' %>");
$("#productModal").modal('show');