config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  namespace :admin do
    get 'rest_books/index'
  end
  namespace :admin do
    get 'hottest_products/index'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web, at: '/sidekiq'
  scope "(:locale)", :locale => /en|vi/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }
    devise_scope :user do
      get "signin", to: "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      post "signin" => "devise/sessions#create"
    end
    root 'static_pages#index'
    resources :books, only: :show do
      put :update_visited
    end
    resources :wishlists
    resources :carts do
      collection do
        delete "destroy_all_cart"
      end
    end
    resources :orders
    resources :categories, only: :show
    resources :notifications
    resources :authors
    # get "/modalbook", to: "static_pages#modalbook"
    namespace :admin do
      root 'static_pages#index'
      resources :categories
      resources :roles
      resources :authors
      resources :users
      resources :books
      resources :orders
      resources :notifications, only: [:update, :index]
      resources :statistic_orders, only: :index
      resources :hottest_products, only: :index
      resources :rest_books, only: :index
    end
  end
  mount ActionCable.server => '/cable'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_book, only: %i(create destroy update)
  skip_before_action :verify_authenticity_token

  def index
    @carts = shopping_cart
  end

  def create
    session[:carts] ||= []
    @cart_services = CartsService.new(params, @book, session[:carts], flash).perform
  end

  def destroy
    session[:carts].each do |item|
      session[:carts].delete(item) if item["book_id"] == @book.id
    end
  end

  def update
    quantity = params[:qty].to_i

    if quantity > @book.quantity
      flash[:danger] = t "quantity_invalid"
    else
      result = find_exist_book_in_cart @book.id
      result["quantity"] = quantity
      if result["quantity"] == 0
        session[:carts].delete(result)
      end
    end
  end

  def destroy_all_cart
    session[:carts] = []
  end

  private

  def find_exist_book_in_cart book_id
    result = nil
    session[:carts].each do |item|
      next unless item["book_id"] == book_id
      result = item
    end
    result
  end

  def load_book
    @book = Book.find_by id: params[:id]
    return if @book
    flash[:danger] = t "wishlists.create.not_found"
    respond_to do |format|
      format.js {render js: "window.location='#{request.referrer}'"}
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<tr>
  <td class="product-image product-cart-img">
    <%= link_to book_path(cart.book) do %>
        <%= image_tag cart.book_image.url %>
    <% end %>
  </td>
  <td class="t-product-name">
    <h3>
      <%= link_to book_path(cart.book) do %>
        <%= cart.book_name %>
      <% end %>
    </h3>
  </td>
  <td class="product-unit-price">
      <p><%= format_money_amount cart.money %></p>
  </td>
  <td class="product-quantity product-cart-details">
    <input type="number" value="<%= cart.quantity %>" data-book-id="<%= cart.book.id %>" data-old-value="<%= cart.quantity %>" class="update-cart-book cart-pro-book-<%= cart.book.id %>">
  </td>
  <td class="product-quantity">
    <p><%= format_money_amount cart.money*cart.quantity %></p>
  </td>
  <td class="product-remove">
    <%= link_to cart_path(cart.book, qty: cart.quantity), method: :put, remote: true do %>
      <i class="fas fa-sync-alt"></i>
    <% end %>
    <%= link_to cart_path(cart.book), method: :delete, remote: true do %>
        <i class="fas fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/carts/create.js.erb
<% if flash[:danger] %>
  Swal.fire({
    icon: 'error',
    title: 'Oops...',
    text: '<%= flash[:danger] %>'
  })
<% else %>
  Swal.fire({
    icon: 'success',
    title: I18n.t('add_cart'),
    showConfirmButton: false,
    timer: 1500
  })
  $('.qty-cart').html('<%= current_quantity %>');
  $('.add-to-cart-product').html('<%= j render "layouts/cart_index" %>');
<% end %>

app/views/carts/destroy.js.erb
Swal.fire({
    icon: 'success',
    title: I18n.t('delete_cart'),
    showConfirmButton: false,
    timer: 1500
  })
$('.qty-cart').html('<%= current_quantity %>');
<% if session[:carts].present? %>
  $('.add-to-cart-product').html('<%= j render "layouts/cart_index" %>');
  $('#list-cart').html('<%= j render partial: "carts/cart", collection: shopping_cart %>');
  $('.total_price_cart').html('<%= format_money_amount total_price %>');
<% else %>
  $('.add-to-cart-product').html('<div class="text-danger text-center not-product"><%= t "not_product" %></div>');
  $('#list-cart').html('<tr class="text-danger text-center not-product"><td colspan="6"><%= t "not_product"%></td></tr>');
  $('.clear-cart').hide();
  $('.discount-area').hide();
<% end %>

app/views/carts/destroy_all_cart.js.erb
Swal.fire({
    icon: 'success',
    title: I18n.t('delete_cart'),
    showConfirmButton: false,
    timer: 2000
})
$('.qty-cart').html('<%= current_quantity %>');
$('.add-to-cart-product').html('<div class="text-danger text-center not-product"><%= t "not_product" %></div>');
$('#list-cart').html('<tr class="text-danger text-center not-product"><td colspan="6"><%= t "not_product"%></td></tr>');
$('.clear-cart').hide();
$('.discount-area').hide();

app/views/carts/index.html.erb
<div class="breadcrumbs-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs">
         <h2>PRODUCT DETAILS</h2>
         <ul class="breadcrumbs-list">
          <li>
            <%= link_to root_path, title: "Return to Home" do %>
              Home
            <% end %>
          </li>
          <li>Product Details</li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
<div class="shopping-cart-area section-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="wishlist-table-area table-responsive">
            <table>
              <thead>
                <tr>
                  <th class="product-image"><%= t "image" %></th>
                  <th class="t-product-name"><%= t "product_name" %></th>
                  <th class="product-unit-price"><%= t "unit_price" %></th>
                  <th class="product-quantity"><%= t "quantity" %></th>
                  <th class="product-subtotal"><%= t "sub_total" %></th>
                  <th class="product-remove"><%= t "action" %></th>
                </tr>
              </thead>
              <tbody id="list-cart">
                <% if session[:carts].present? %>
                  <%= render partial: "carts/cart", collection: @carts %>
                <% else %>
                  <tr class="text-danger text-center not-product">
                    <td colspan="6"><%= t "not_product" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>
        <div class="shopingcart-bottom-area">
          <%= link_to root_path, class: "left-shoping-cart" do %>
            CONTINUE SHOPPING
          <% end %>
          <% if session[:carts].present? %>
            <div class="shopingcart-bottom-area pull-right clear-cart">
              <%= link_to destroy_all_cart_carts_path, method: :delete, remote: true, class: "right-shoping-cart" do %>
                CLEAR SHOPPING CART
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if session[:carts].present? %>
  <div class="discount-area">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 checkout-block">
          <div class="subtotal-main-area">
            <div class="subtotal-area">
                <h2>GRAND TOTAL<span class="total_price_cart"><%= format_money_amount total_price %></span></h2>
            </div>
            <%= link_to new_order_path do %>
              <%= t "checkout" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/carts/update.js.erb
<% if flash[:danger] %>
  Swal.fire({
    icon: 'error',
    title: 'Oops...',
    text: '<%= flash[:danger] %>'
  })
<% else %>
  Swal.fire({
    icon: 'success',
    title: I18n.t('update_cart'),
    showConfirmButton: false,
    timer: 1500
  })
  $('.qty-cart').html('<%= current_quantity %>');
  <% if session[:carts].present? %>
    $('.add-to-cart-product').html('<%= j render "layouts/cart_index" %>');
    $('#list-cart').html('<%= j render partial: "carts/cart", collection: shopping_cart %>');
    $('.total_price_cart').html('<%= format_money_amount total_price %>')
  <% else %>
    $('.add-to-cart-product').html('<div class="text-danger text-center not-product"><%= t "not_product" %></div>');
    $('#list-cart').html('<tr class="text-danger text-center not-product"><td colspan="6"><%= t "not_product"%></td></tr>');
    $('.clear-cart').hide();
    $('.discount-area').hide();
  <% end %>
<% end %>