config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  namespace :admin do
    get 'rest_books/index'
  end
  namespace :admin do
    get 'hottest_products/index'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web, at: '/sidekiq'
  scope "(:locale)", :locale => /en|vi/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }
    devise_scope :user do
      get "signin", to: "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      post "signin" => "devise/sessions#create"
    end
    root 'static_pages#index'
    resources :books, only: :show do
      put :update_visited
    end
    resources :wishlists
    resources :carts do
      collection do
        delete "destroy_all_cart"
      end
    end
    resources :orders
    resources :categories, only: :show
    resources :notifications
    resources :authors
    # get "/modalbook", to: "static_pages#modalbook"
    namespace :admin do
      root 'static_pages#index'
      resources :categories
      resources :roles
      resources :authors
      resources :users
      resources :books
      resources :orders
      resources :notifications, only: [:update, :index]
      resources :statistic_orders, only: :index
      resources :hottest_products, only: :index
      resources :rest_books, only: :index
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.max_length_category_name}

  scope :created_desc, ->{order created_at: :desc}

  def enable_status_i18n
    I18n.t("admin.roles.index.is_enable.#{enable}")
  end
end

app/controllers/admin/roles_controller.rb
module Admin
  class RolesController < AdminBaseController
    before_action :find_role, only: %i(edit update destroy)

    def index
      @roles = Role.created_desc.page(params[:page]).per Settings.paginate.show_15
    end

    def new
      @role = Role.new
    end

    def create
      @role = Role.new role_params

      if @role.save
        flash[:success] = t ".success"
        redirect_to admin_roles_path
      else
        flash[:danger] = t ".fail"
        render :new
      end
    end

    def edit; end

    def update
      if @role.update_attributes role_params
        flash[:success] = t ".success"
        redirect_to admin_roles_path
      else
        flash[:danger] = t ".fail"
        render :edit
      end
    end

    def destroy
      @roles = Role.created_desc.page(params[:page]).per Settings.paginate.show_15

      if @role.destroy
        flash[:success] = "Destroy success"
      else
        flash[:danger] = "Destroy fail"
      end
    end

    private

    def role_params
      params.require(:role).permit :name, :description, :enable
    end

    def find_role
      @role = Role.find_by id: params[:id]
      return if @role
      flash[:danger] = t "admin.roles.create.not_found"
      redirect_to admin_roles_path
    end
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<div class="modal-dialog form-category">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title"><%= title %></h4>
      <button type="button" class="btn btn-danger" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <%= simple_form_for [:admin, @role], remote: true, authenticity_token: true, html: {novalidate: true, class: "js-form-category no-bs-validation"} do |f| %>
        <div class="row form-group">
          <div class="col-md-12">
            <%= f.input :name, placeholder: t(".name"), label: t(".name"),
              input_html: {class: "form-control js-category-name"} %>
          </div>
        </div>
        <div class="row form-group">
          <div class="col-md-12">
            <%= f.cktext_area :description,
              placeholder: t(".content"), label: t(".content"),
              input_html: {class: "form-control js-category-description"} %>
          </div>
        </div>
        <div class="row form-group">
          <div class="col-md-4">
            <%= f.input :enable, label: t(".status"), input_html: {class: "form-control js-category-is_enable"},
              label_html: {class: "col-md-3 switch-btn-category"}, content_html: {class: "col-md-3"},
              input_group_html: {class: "input-group"} do %>
                <label class="switch switch-primary">
                  <%= f.check_box :enable, {checked: (@role.persisted? ? @role.enable : true)} %>
                  <span></span>
                </label>
            <% end %>
        </div>
          </div>
        <div class="row form-group">
          <div class="col-md-12 text-right">
            <%= f.button :submit, type: "submit", title: t(".save"),
              class: "btn btn-sm btn-primary js-button-form-category" do %>
              <i class="fa fa-floppy-o" aria-hidden="true"></i>
              <%= t ".save" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/roles/_role.html.erb
<tr>
  <td class="text-center" >
    <%= create_index params[:page], role_counter, Settings.paginate.show_15 %>
  </td>
  <td class="text-center"><strong><%= role.name %></strong></td>
  <td><%= raw role.description %></td>
  <td class="text-center">
    <p class="label label_category_<%= role.enable %>">
      <%= role.enable_status_i18n %>
    </p>
  </td>
  <td class="text-center" >
    <div class="btn-group option">
      <%= link_to edit_admin_role_path(role), class: "btn btn-xs btn-primary button-custom",
        title: t(".edit"), remote: true do %>
        <i class="fa fa-pencil-alt" aria-hidden="true""></i>
      <% end %>
    </div>
    <div class="btn-group option">
      <%= button_tag class: "btn btn-xs btn-danger delete-role-button button-custom-danger",
        title: t(".delete"), data: {id: role.id, name: role.name} do %>
        <i class="fa fa-trash icon"></i>
      <% end %>
    </div>
    </div>
  </td>
</tr>

app/views/admin/roles/destroy.js.erb
<% if flash[:success] %>
  toastr.success("<%= flash[:success] %>")
<% end %>
<% if flash[:warning] %>
  toastr.warning("<%= flash[:warning] %>")
<% end %>
<% if flash[:danger] %>
  toastr.error("<%= flash[:danger] %>")
<% end %>
$('#list-roles').html('<%= j render @roles %>')

app/views/admin/roles/edit.js.erb
$('#role-modal').html('<%= j render "form", title: I18n.t("admin.roles.new.edit_title") %>')
$('#role-modal').modal('show');

app/views/admin/roles/index.html.erb
<div class="content-header">
  <div class="header-section">
    <h1>
      <%= t ".role_management" %>
    </h1>
  </div>
</div>
<div class="block full">
  <div class="block-title">
    <p><strong><%= t ".list_roles" %></strong></p>
  </div>
  <div class="table-responsive test-created-table">
    <div class="dataTables_wrapper">
      <div class="row add-new">
        <div class="col-md-3 mb-10 remove-padding pb-4">
          <div>
            <%= link_to new_admin_role_path, class: "btn btn-primary margin-left-5 new-cate", remote: true do %>
              <i class="fa fa-plus"></i> <%= t ".new_role" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-body table-responsive p-0">
              <table class="table table-hover text-nowrap">
                <thead>
                  <tr>
                    <th class="text-center"><%= t ".index" %></th>
                    <th class="text-center"><%= t ".name" %></th>
                    <th><%= t ".description" %></th>
                    <th class="text-center"><%= t ".status" %></th>
                    <th class="text-center"><%= t ".action" %></th>
                  </tr>
                </thead>
                <tbody id="list-roles">
                  <%= render @roles %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="pagination">
      <%= paginate @roles %>
    </div>
  </div>
</div>
<div id="role-modal" class="modal fade" data-backdrop="static"></div>

app/views/admin/roles/new.js.erb
$('#role-modal').html('<%= j render "form", title: I18n.t("admin.roles.new.create_title") %>')
$('#role-modal').modal('show');