config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  namespace :admin do
    get 'rest_books/index'
  end
  namespace :admin do
    get 'hottest_products/index'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web, at: '/sidekiq'
  scope "(:locale)", :locale => /en|vi/ do
    devise_for :users, controllers: {
      sessions: "users/sessions"
    }
    devise_scope :user do
      get "signin", to: "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      post "signin" => "devise/sessions#create"
    end
    root 'static_pages#index'
    resources :books, only: :show do
      put :update_visited
    end
    resources :wishlists
    resources :carts do
      collection do
        delete "destroy_all_cart"
      end
    end
    resources :orders
    resources :categories, only: :show
    resources :notifications
    resources :authors
    # get "/modalbook", to: "static_pages#modalbook"
    namespace :admin do
      root 'static_pages#index'
      resources :categories
      resources :roles
      resources :authors
      resources :users
      resources :books
      resources :orders
      resources :notifications, only: [:update, :index]
      resources :statistic_orders, only: :index
      resources :hottest_products, only: :index
      resources :rest_books, only: :index
    end
  end
  mount ActionCable.server => '/cable'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_types
  has_many :books, through: :category_types

  validates :name, presence: true, length: {maximum: Settings.max_length_category_name}

  scope :created_desc, ->{order created_at: :desc}

  def enable_status_i18n
    I18n.t("admin.categories.index.status_work.#{status}")
  end
end

app/models/category_type.rb
class CategoryType < ApplicationRecord
  belongs_to :category
  belongs_to :book

  scope :by_category_ids, -> (category_ids){where category_id: category_ids}
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < AdminBaseController
    before_action :find_category, only: %i(destroy edit show update)

    def index
      @categories = Category.created_desc.page(params[:page]).per Settings.paginate.show_15
    end

    def new
      @category = Category.new
    end

    def edit; end

    def update
      if @category.update_attributes category_params
        flash[:success] = t ".update_success"
        redirect_to admin_categories_path
      else
        flash[:danger] = t ".update_failed"
        render :edit
      end
    end

    def show; end

    def create
      @category = Category.new category_params

      if @category.save
        flash[:success] = t ".create_success"
        redirect_to admin_categories_path
      else
        flash[:danger] = t ".create_fail"
        render :new
      end
    end

    def destroy
      @categories = Category.created_desc.page(params[:page]).per Settings.paginate.show_15
      if @category.destroy
        flash[:success] = t ".success"
      else
        flash[:danger] = t ".failed"
      end
    end

    private

    def category_params
      params.require(:category).permit :name, :description, :status
    end

    def find_category
      @category = Category.find_by id: params[:id]
      return if @category
      flash[:danger] = "Khong tim thay the loai nay"
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    if params[:price]
      a = params[:price].split("-")[0].gsub("\,", "")
      b = params[:price].split("-")[1].gsub("\,", "")
      @q = Book.includes(:categories).by_category(params[:id]).between_price(a, b).search params[:q]
    else
      @q = Book.includes(:categories).by_category(params[:id]).search params[:q]
    end
    @categories = Category.select(:id, :name)
    @category = Category.find_by id: params[:id]
    @books = @q.result(distinct: true)
    @top_books = Book.top_product
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_grid.html.erb
<% @books.each do |book| %>
  <% if user_signed_in? %>
    <% wishlist = Wishlist.find_by user_id: current_user.id, book_id: book.id %>
  <% end %>
  <div class="shop-single-product-area">
    <div class="col-md-4 col-sm-6">
      <div class="single-banner">
        <div class="product-wrapper">
          <%= link_to book_path(book), class: "single-banner-image-wrapper check-visited", data: {book_id: book.id} do %>
            <%= image_tag book.image.url %>
            <div class="price"><%= format_money_amount book.money %></div>
          <% end %>
          <div class="product-description">
            <div class="functional-buttons button-reaction-<%= book.id %>">
              <%= render "static_pages/button_book", book: book, wishlist: wishlist %>
            </div>
          </div>
        </div>
        <div class="banner-bottom text-center">
          <div class="banner-bottom-title">
            <%= link_to book.name, book_path(book), class: "check-visited", data: {book_id: book.id} %>
          </div>
          <div class="rating-icon">
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/_list.html.erb
<div class="row">
  <% @books.each do |book| %>
    <div class="single-shop-product">
      <div class="col-xs-12 col-sm-5 col-md-4">
        <div class="left-item">
          <%= link_to book_path(book), class: "single-banner-image-wrapper check-visited", data: {book_id: book.id} do %>
            <%= image_tag book.image.url %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-7 col-md-8">
        <div class="deal-product-content">
          <h4>
            <%= link_to book.name, book_path(book), class: "check-visited", data: {book_id: book.id} %>
          </h4>
          <div class="product-price">
            <span class="new-price"><%= format_money_amount book.money %></span>
          </div>
          <div class="list-rating-icon">
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star icolor"></i>
            <i class="fas fa-star"></i>
            <i class="fas fa-star"></i>
          </div>
          <p><%= book.description.html_safe %></p>
          <div class="availability">
            <% if book.quantity > 0 %>
              <span>In stock</span>
              <span>
                <%= link_to t("add_to_cart"), carts_path(id: book.id, price: book.money, qty: 1), remote: true, method: :post, title: t("add_to_cart") %>
              </span>
            <% else %>
              <span class="out-stock">Out of stock</span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/_search_bar.html.erb
<div class="col-md-3 col-sm-3 col-xs-12">
  <div class="shop-widget">
    <div class="shop-widget-top">
      <aside class="widget widget-categories">
        <h2 class="sidebar-title text-center"><%= t "category" %></h2>
        <ul class="sidebar-menu">
          <% @categories.each do |category| %>
            <li>
              <%= link_to category_path(category) do %>
                 <i class="fas fa-angle-double-right"></i>
                  <%= category.name %>
                  <span>(<%= category.books.size %>)</span>
              <% end %>
            </li>
          <% end %>
        </ul>
      </aside>
      <aside class="widget shop-filter">
        <h2 class="sidebar-title text-center"><%= t "search_by_name" %></h2>
        <div class="info-widget">
          <%= search_form_for @q, url: category_path do |f| %>
            <%= f.text_field :name_cont, class: "search_name form-control" %>
            <div class="widget-buttom">
              <%= f.submit t("filter"), class: "button-search-name" %>
              <%= f.submit t("clear"), type: "reset", class: "button-search-name" %>
            </div>
          <% end %>
        </div>
      </aside>
      <hr>
      <aside class="widget shop-filter">
        <h2 class="sidebar-title text-center"><%= t "price_slider" %></h2>
        <div class="info-widget">
          <div class="price-filter">
              <div id="slider-range" class="range-bar"></div>
              <div class="price-slider-amount">
                <%= search_form_for @q, url: category_path do |f| %>
                  <%= f.text_field :money, id: "amount", name: "price", placeholder: "Add Your Price" %>
                  <div class="widget-buttom">
                      <%= f.submit t("filter") %>
                      <%= f.submit t("clear"), type: "reset" %>
                  </div>
                <% end %>
              </div>
          </div>
        </div>
      </aside>
    </div>
    <div class="shop-widget-bottom">
      <aside class="widget widget-seller">
        <h2 class="sidebar-title">TOP SELLERS</h2>
        <% @top_books.each do |book| %>
          <div class="single-seller">
            <div class="seller-img">
              <%= image_tag book.image.url %>
            </div>
            <div class="seller-details">
                <%= link_to book_path(book) do %>
                  <h5><%= book.name %></h5>
                <% end %>
                <h5><%= format_money_amount book.money %></h5>
                <ul>
                    <li><i class="fas fa-star icolor"></i></li>
                    <li><i class="fas fa-star icolor"></i></li>
                    <li><i class="fas fa-star icolor"></i></li>
                    <li><i class="fas fa-star icolor"></i></li>
                    <li><i class="fas fa-star icolor"></i></li>
                </ul>
            </div>
          </div>
        <% end %>
      </aside>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="breadcrumbs-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumbs">
         <h2>PRODUCT DETAILS</h2>
         <ul class="breadcrumbs-list">
          <li>
            <%= link_to root_path, title: "Return to Home" do %>
            Home
            <% end %>
          </li>
          <li>Product</li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
<div class="shopping-area section-padding">
  <div class="container">
    <div class="row">
      <%= render "search_bar" %>
      <div class="col-md-9 col-sm-9 col-xs-12">
        <div class="shop-tab-area">
          <div class="shop-tab-list">
            <div class="shop-tab-pill pull-left">
              <ul>
                <li class="active" id="left">
                  <%= link_to category_path(@category, view: "grid"), remote: true, class: "type-view grid" do %>
                    <i class="fas fa-th"></i><span>Grid</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to category_path(@category, view: "list"), remote: true, class: "type-view list" do %>
                    <i class="fas fa-th-list"></i><span>List</span>
                  <% end %>
                </li>
              </ul>
            </div>
            <div class="shop-tab-pill pull-right">
              <ul>
                <li class="product-size-deatils">
                  <div class="show-label">
                    <label>Show : </label>
                    <select>
                      <option value="10" selected="selected">10</option>
                      <option value="09">09</option>
                      <option value="08">08</option>
                      <option value="07">07</option>
                      <option value="06">06</option>
                    </select>
                  </div>
                </li>
                <li class="product-size-deatils">
                  <div class="show-label">
                    <label><i class="fas fa-sort-amount-asc"></i>Sort by : </label>
                    <select>
                      <option value="position" selected="selected">Position</option>
                      <option value="Name">Name</option>
                      <option value="Price">Price</option>
                    </select>
                  </div>
                </li>
                <li class="shop-pagination"><a href="#">1</a></li>
                <li class="shop-pagination"><a href="#">2</a></li>
                <li class="shop-pagination"><a href="#"><i class="fas fa-caret-right"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="tab-content shopping-page">
            <div class="row tab-pane fade in active" id="home" class="grid">
              <%= render "categories/grid" %>
            </div>
            <div id="menu1" class="tab-pane fade" class="list">
              <%= render "categories/list" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.js.erb
<% if params[:view] == 'grid' %>
  $('.shopping-page #menu1').removeClass('in active');
  $('.shopping-page #home').addClass('in active');
  $('.shopping-page #home').html('<%= j render "categories/grid" %>');
<% else %>
  $('.shopping-page #home').removeClass('in active');
  $('.shopping-page #menu1').addClass('in active');
  $('.shopping-page #menu1').html('<%=j render "categories/list" %>');
<% end %>